#ifdef PLATFORM_ARDUINO_UNO
  #define PLATFORM_LITTLE_ENDIAN
#endif

#ifdef PLATFORM_ARDUINO_DUE
  #define PLATFORM_LITTLE_ENDIAN
#endif

#ifdef PLATFORM_ESP32
  #define PLATFORM_LITTLE_ENDIAN
#endif
